name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        os: [ubuntu-24.04, macos-15, windows-2025]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-15'
        run: |
          brew update
          brew install ninja sqlite3

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-24.04'
        env:
          CXX: g++-13
          CC: gcc-13
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libsqlite3-dev gcc-13 g++-13

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-2025'
        run: |
          choco install ninja

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-2025'
        shell: bash
        run: |
          choco install ninja
          curl https://www.sqlite.org/2026/sqlite-amalgamation-3510200.zip -o sqlite.zip
          unzip

      - name: Configure
        run: |
          # On modern macOS /var/ is a symlink. By default the library doesn't allow following symlinks.
          # The tests uses std::filesystem::temp_directory_path() which returns a path in /var, causing
          # tests to fail so we explicitly allow it.
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DVSQLITE_BUILD_EXAMPLES=ON -DVSQLITE_ALLOW_FOLLOW_SYMLINKS=ON
        shell: bash

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --test-dir build --verbose --build-config ${{ matrix.build_type }}
